title: "白骨观"
theme: "docs"
paginate: 10
baseURL: "http://baiguguan.cn/"
defaultContentLanguage: "zh"

params:
  siteLogo: logo.svg
  description: "白骨观是佛家修持法之一，为佛教五门禅法之一种，通常由不净观、白骨观、白骨生肌和白骨流光四步组成。主要的目的是息灭对色身的贪恋并厌恶另一半。"
  keywords: "白骨观, 佛家, 五门禅法, 不净观, 白骨观,白骨生肌,白骨流光"
  author: "JQX"
  disableToc: false
  menu:
    expandAll: true
    maxLevel: 3   # Available value is 1-3
    maxPages: 20  # Maximum pages to show in the menu, the value is 10 by default

#defaultContentLanguageInSubdir: false
languages:
  zh:
    contentDir: "content"
    disabled: false
    languageCode: "zh-cn"
    languageDirection: "ltr"
    languageName: "简体中文"
    weight: 1
    
markup:
  highlight:
    lineNos: false
    style: github
  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: false
    
services:
  disqus:
    shortname:
    
taxonomies:
  series: "series"
